modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="bc"
version="1.0.0"
displayName="Beyond Creation"
displayURL="https://github.com/Gavirium/Beyond-Creation-1.21.1-neoforge"
credits="Textures and code by Gavirium"
authors="Gavirium"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.bc]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bc]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.bc]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration